### ISSUE TITLE
output of objects doesn't print their properties values

### ISSUE THREAD

**Issue by avner-hoffmann** [megahertz/electron-log#125]
I've upgraded electron-log from version 2.2.17 to the latest 3.0.3
on the latest version printing objects from the renderer process outputs the properties type (and not their values)

e.g. if I have a JS object:

`const obj = {
   username: 'Me'
};`

When printing the object using one of the log's functions I'm getting:
{ username: [Getter/Setter] }

This wasn't the case in the previous 2.x releases...

**Comment by megahertz** [comment]
Do you pass the plain object, or use some tool which sets this getter/setter instead of the username property?

**Comment by avner-hoffmann** [comment]
The object is a Vuex state object, but the username property is of a primitive type. 
Vuex wraps every reactive object property with a getter/setter. 
It didn't happen on version 2.2.17, I think it's a regression

**Comment by megahertz** [comment]
Thank you. Will fix later.

**Comment by fjrial** [comment]
Using electron-log version 3.0.5

The already provided fix, will output first nested object properties correctly. Thanks.
But it the object contains **nested** properties with their getters/setters, they are not printed to the log.log file. **But in the console all info is printed correctly**.

Example from the log.log file:
`[2019-04-04 10:10:33.863] [info] Loaded project config...`
`[2019-04-04 10:10:33.869] [info] { name: [Getter/Setter],`
  `comments: [Getter/Setter],`
  `approach: [Getter/Setter],`
  `filenames: [Getter/Setter],`
  `filesettings: [Getter/Setter],`
  `globalParameters: [Getter/Setter],`
  `ids: [Getter/Setter],`
  `modelsSelected: [Getter/Setter]`

I changed code in format.js file to allow a printable view of the objects:
`function stringifyArray(data) {`
`  if (typeof data === 'object'){`
`    data = JSON.stringify(data);`
`    return data;`
`  }`
`  else{`
`    data = data.map(stringifyObject);`
`    if (util.formatWithOptions) {`
`      return util.formatWithOptions.apply(util, [{ getters: true }].concat(data));`
`    }`
`    return util.format.apply(util, data);`
`  }`
`}`

Do you think this could be a problem ?? Maybe some performance issues if the object is too big??
Also, I'm seeing the output in the console, but I disabled the console logging (in renderer/main.js) using (maybe I should filled another issue??)
`log.transports.console.level = false;`

**Comment by megahertz** [comment]
@fjrial Will look at the problem later.

It seems that you receive console message form mainConsole/rendererConsole. #122. I know it can confuse someone, so I have a plan to change its interface later.

**Comment by fjrial** [comment]
While trying my changes on your code, I realized that the error messages are also "Objects", and they get JSON.stringified, and because of this, the error trace is missing when saved to the log file.

As it is right now, this is an error message logged in the file:
`[2019-04-04 13:15:14.624] [error] [{"errno":-4058,"code":"ENOENT","syscall":"open","path":"C:\\Users\\Jrial\\AppData\\Roaming\\Affinimeter-ITC-Advanced\\Affinimeter-ITC-Advanced\\data\\itc\\1554376527925.9\\OOOOOOOOOOOOOOOO+menos-inxeccions.ITC","name":"UnhandledRejection Error"}]`

With a little change, the same error logged is more helpful for debugging:
`[error] UnhandledRejection Error: ENOENT: no such file or directory, open 'C:\Users\Jrial\AppData\Roaming\Affinimeter-ITC-Advanced\Affinimeter-ITC-Advanced\data\itc\1554376598550.61\OOOOOOOOOOOOOOOO+menos-inxeccions.ITC'
    at Object.fs.openSync (fs.js:652:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:172:20)
    at Object.fs.readFileSync (fs.js:553:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:508:29)
    at affKinItc.ReadSettingsItcFile (webpack-internal:///13:243:29)
    at affKinItc.ReadSettingsItcFileFromFolder (webpack-internal:///13:175:33)
    at eval (webpack-internal:///141:223:90)
    at Promise (<anonymous>)
    at F (webpack-internal:///28:36:28)
    at VueComponent.getFileInfo (webpack-internal:///141:222:14)`

So, I ended up with a little change to the previous code
`if ((typeof data === 'object') && (typeof data.errno !=='undefined')){`

I was trying to check for the instanceof Error boolean, but didn´t succeed
`if ((typeof data === 'object') && (!(data instanceof Error))){`

Thank you

**Comment by leegee** [comment]
Presumably related, logging HTMLInputElements and Events from the DOM produces misleading results.

**Comment by avner-hoffmann** [comment]
Hi, anything new with this?

**Comment by megahertz** [comment]
It'll be fixed in v4
