### ISSUE TITLE
Common log path utilities split into their own repo

### ISSUE THREAD

**Issue by JoshuaGross** [megahertz/electron-log#13]
Just FYI, in case you find this useful or interesting, I split out some common utilities around finding application logging directories, made it a bit more robust and made it async: https://github.com/JoshuaGross/app-log-dir

This isn't a feature request but it would simplify the core logic of `electron-log` to rely on this library, if you like! I've given you proper attribution in that repo as well. Cheers!

**Comment by megahertz** [comment]
Hi Joshua. 
Thank you for the suggestion. There are some reasons why I made this package by that way.
First of all, I don't use async functions because I want to save a log record before other operations. Yes, It can decrease performance a bit, but sometimes it's strongly necessary.
At second, I try to follow KISS principles while it's possible. That's why I don't use dependencies and js compilers for tiny projects when it's possible.
But you are right that now the index.js is growing and I'll need to separate it soon.
Anyway, your library is good for other situations!
