### ISSUE TITLE
Default Windows location should be %LOCALAPPDATA%

### ISSUE THREAD

**Issue by LambdaGoblin** [megahertz/electron-log#134]
On Windows, the %APPDATA% variable is the user's roaming profile, which means log files are transferred from the server and back when a roaming user logs in and out.  This is wasteful and unnecessary, it would be better to use %LOCALAPPDATA% which is non-roaming.

If the change cannot be made due to too many dependent projects, it would be good to have an easy way to specify that a non-roaming log path would be preferred.

**Comment by megahertz** [comment]
I decided to use APPDATA because electron stores all its assets here (caches, stores, internal logs and so on). Most of electron-related packages use the same location too (mostly, because of app.getPath('userData)). Yes, it's not a perfect way, but I see no reason use LOCALAPPDATA opposite to these solutions. That's also the reason why I use ~/.config on linux instead of ~/.local/share which is better place.

**Comment by LambdaGoblin** [comment]
It's a shame that electron developers in general care so little for being good citizens on every platform.  Very disappointing.
