### ISSUE TITLE
clear old log

### ISSUE THREAD

**Issue by jupit3r13** [megahertz/electron-log#247]
hi @megahertz  . how can i remove or clear log file?

i used:

```
autoUpdater.logger = require("electron-log");
autoUpdater.logger.transports.file.level = "info";
```
` autoUpdater.logger.transports.file.getFile('main.old').clear();`

with this line nothing happens.

and i have another question, when i have error like this message : 

```
 [error] Cannot download differentially, fallback to full download: Error: Cannot parse blockmap ........ 
�   � �	�!�L�!This program cannot be run in DOS mode ........
```

my log file becomes 80mb ! is this problem on autoUpdater side or electron-log side?

**Comment by megahertz** [comment]
Hi. First of all, getFile() should be called without arguments. The library doesn't handle old log, so it should be removed manually.

As for another question, updater receives wrong file and tries to log that. So, it logs 80mb at once. The library doesn't check the size of log message before writing since it's not necessary in most cases.

**Comment by jupit3r13** [comment]
thanks .
