### ISSUE TITLE
Can not log when `undefined` return by getAppName()

### ISSUE THREAD

**Issue by henrydf** [megahertz/electron-log#418]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Recently, my project can not log any more in production env. And it reports `The "path" argument must be of type string. Received undefined`.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/electron-log/src/node/NodeExternalApi.js b/node_modules/electron-log/src/node/NodeExternalApi.js
index 7c5359f..5257a42 100644
--- a/node_modules/electron-log/src/node/NodeExternalApi.js
+++ b/node_modules/electron-log/src/node/NodeExternalApi.js
@@ -21,7 +21,7 @@ class NodeExternalApi {
   }
 
   getAppName() {
-    return this.appName || this.getAppPackageJson()?.name;
+    return this.appName || this.getAppPackageJson()?.name || 'default';
   }
 
   /**
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by megahertz** [comment]
Thank you. I'll investigate that this week

**Comment by megahertz** [comment]
It happens when the library can't load the app name from `electron.app` or `package.json` (there is no package.json file in the current or any parent dir). I don't want to provide a default value for this case since it isn't an expected behavior. Instead, I'm thinking about a way how it can be set through config and throw an exception when it's still empty.
